ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Store Patterns
    path('', include(('store.urls', 'store'), namespace='store')),
    # Cart Pattern
    path('', include(('store.urls', 'cart'), namespace='cart')),
    # Checkout Patterns
    path('', include(('store.urls', 'checkout'), namespace='checkout')),
    # Process Order Patterns
    path('', include(('store.urls', 'process_order'), namespace='process_order')),
    # Checkout Patterns
    path('', include(('store.urls', 'nodeR'), namespace='nodeR')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

store/urls.py
""" Store URLs. """

# Django
from django.urls import  path

# View
from store import views

# Views
urlpatterns = [
 
    # Home page
    path(
        route='',
        view=views.store_view,
        name='store'
    ),
    # Cart
    path(
        route='cart/',
        view=views.cart_view,
        name='cart'
    ),
    # Checkout
    path(
        route='checkout/',
        view=views.checkout_view,
        name='checkout'
    ),

    # Update item
    path(
        route='update_item/',
        view=views.updateItem,
        name='update_item'
    ),

    # Process Order view
    path(
        route='process_order/',
        view=views.processOrder,
        name='process_order'
    ),

    # Process Order view
    path(
        route='nodeR/',
        view=views.nodeRed,
        name='nodeR'
    )


]

store/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    


    # Fixed choice fields

    MOTOR_HP = (
         ('1.0', '1.0'),
         ('2.0', '2.0'),
         ('3.0', '3.0'),
         ('5.0', '5.0'),
         ('10.0', '10.0'),
    )

    MOTOR_SPEED = (
         ('1200', '1200'),
         ('1800', '1800'),
         ('3600', '3600'),
            
    )

    PHASES = (
        ('1', 'Single Phase'),
        ('3', 'Three Phase'),
    )

    PURPOSE = (
        ('General Purpose', 'General Purpose'),
        ('Pump', 'Pump'),
        ('Fan', 'Fan')
    )

     
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    digital = models.BooleanField(default=False, null=True, blank=False)
    description = models.CharField(max_length=600, null=True, blank=False) #widget=forms.Textarea
    
    # Fixed choice fields
    power = models.CharField(max_length=10, choices=MOTOR_HP, null=True, blank=True)
    speed = models.CharField(max_length=10, choices=MOTOR_SPEED, null=True)
    phases_number = models.CharField(max_length=10, choices=PHASES, null=True)
    purpose = models.CharField(max_length=15, choices=PURPOSE, null=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name # This variable is going to be visible when I make a query
    
    # This decorator avoid the error when an image file is empty
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
            if url ==    '':
                url = '/static/images/placeholder.png'
        return url


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)
    
    def __str__(self):
        return str(self.id)

    # Set the logic to shipping or not shipping address
    @property
    def shipping(self):
        shipping = False
        orderItems = self.orderitem_set.all()

        for i in orderItems:
            if i.product.digital == False:
                shipping = True
        return shipping

    
    # To sum the total cost of each of the order items
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([ orderitem.get_total for orderitem in orderitems])
        return total
    
    # To sum each of the order items quantity
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([orderitem.quantity for orderitem in orderitems])
        return total
    


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True) 
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True) 
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.product.name)
    
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True) # Check this
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    data_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

store/forms.py
from django import forms


# Fixed choice fields

MOTOR_HP = (
    (' ', 'Select'),
    ('1.0', '1.0'),
    ('2.0', '2.0'),
    ('3.0', '3.0'),
    ('5.0', '5.0'),
    ('10.0', '10.0'),
)

MOTOR_SPEED = (
    (' ', 'Select'),
    ('1200', '1200'),
    ('1800', '1800'),
    ('3600', '3600'),
    
)

PHASES = (
    (' ', 'Select'),
    ('1', 'Single Phase'),
    ('3', 'Three Phase'),
)

PURPOSE = (
    (' ', 'Select'),
    ('General Purpose', 'General Purpose'),
    ('Pump', 'Pump'),
    ('Fan', 'Fan')
)


class MotorFilterForm(forms.Form):

    power = forms.ChoiceField(choices=MOTOR_HP, required=True,
        label='Power [HP]')
    
    speed = forms.ChoiceField(choices=MOTOR_SPEED, required=True, 
        label="Speed [RPM]")
    
    phases = forms.ChoiceField(choices=PHASES, required=True,
        label="Phases")
    
    purpose = forms.ChoiceField(choices=PURPOSE, required=True, 
        label="Purpose")
    

store/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
import json
import datetime
# Models
from .models import * # Import all models from this folder

# Forms
from store.forms import MotorFilterForm

# Utilities
import pdb
from . utils import cookieCart, cartData, guestOrder

# Create your views here.


def store_view(request):
    """ The main store view."""
    # AUTHENTICATED VALIDATION CODE
    # For authenticated users
    if request.user.is_authenticated:
        customer = request.user.customer
        # Creates a empty order with the field "complete" set to False
        order, created = Order.objects.get_or_create(customer=customer, 
            complete=False
        ) # Search for an order that has already incomplete or create a new
        items = order.orderitem_set.all() # Querying the child objects within orderitems
        cartItems = order.get_cart_items
        #pdb.set_trace()
    # For unauthenticated users
    else:
        cookieData = cookieCart(request)
        cartItems = cookieData['cartItems']

    # FILTER CODE    
    # return HttpResponse('Ecommerce App!')
    products = Product.objects.all() # Making the Query
    #pdb.set_trace()
    
    if request.method =='POST':
        """ If the formulary has been submitted [ the filter button has been pressed, then the following queryset is sent: (Pdb) request.POST <QueryDict: {'csrfmiddlewaretoken': ['oNfJlX2vP6bF32DSk6LGpA6A8HUoqgp4l3K02yUORlk5Mzm66vhL2tATsdJMFhoX'], 'power': ['1.0']}>]"""
        form = MotorFilterForm(request.POST) # Load the form, create a form instance and populate it with data from the request
        #pdb.set_trace()
        # check whether it's valid:
        if form.is_valid():
            
            # Filtering
            hp_query = request.POST.get('power') 
            speed_query = request.POST.get('speed') 
            phases_query = request.POST.get('phases')
            purpose_query = request.POST.get('purpose')

            #pdb.set_trace()
            
            if hp_query != ' ' and hp_query is not None:
                products = products.filter(power=hp_query)

            if speed_query != ' ' and speed_query is not None:
                products = products.filter(speed=speed_query)

            if phases_query != ' ' and phases_query is not None:
                products = products.filter(phases_number=phases_query)

            if purpose_query != ' ' and purpose_query is not None:
                products = products.filter(purpose=purpose_query)

    else: # if a GET (or any other method) we'll create a blank form
        form = MotorFilterForm() # Send an empty formulary
        #products = Product.objects.all() # Making the Query
        #order = {'get_cart_total':0, 'get_cart_items':0} # Send this empty dict to avoid error on the browser
        #cartItems = order['get_cart_order']

    return render(
        request=request,
        template_name='store/store.html',
        context={
            'products': products, # Envía el contexto al template
            'form': form,
            'cartItems': cartItems,
        }
    )

def cart_view(request):
    
    data = cartData(request)

    items = data['items']
    order = data['order']
    cartItems = data['cartItems']

        #pdb.set_trace()

    return render(
        request=request,
        template_name='store/cart.html',
        context={
            'items': items,
            'order': order,
            'cartItems': cartItems,
            
        }
    )

def checkout_view(request):

    data = cartData(request)

    items = data['items']
    order = data['order']
    cartItems = data['cartItems']


    return render(
        request=request,
        template_name='store/checkout.html',
        context={
            'items': items,
            'order': order,
            'cartItems': cartItems,
        }
    )

def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    #pdb.set_trace()

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1 )
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1 )
    
    orderItem.save()
    
    if orderItem.quantity  <= 0:
        orderItem.delete()

    print('Action:', action)
    print('productId:', productId)

    return JsonResponse('Item was added', safe=False)

def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body) # Receive the form & shipping info data from "checkout.html" javascript
    #pdb.set_trace()

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)


    else:
        customer, order = guestOrder(request, data)
        


    total = float(data['form']['total'])
    order.transaction_id = transaction_id
    
    if total == float(order.get_cart_total): # If the frontend total value is equal to the backend total value
        order.complete = True
    order.save()
            #pdb.set_trace()
    if order.shipping == True:

        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
        )


    return JsonResponse('Payment complete!', safe=False) # Send response data to javascript







def nodeRed(request):

    if request.method == 'POST':
        data = request.POST
    else:
        data ={}

    return render(
        request=request,
        template_name='store/nodeR.html',
        context={
            'data': data,
        }
    )

templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">

				<a  class="btn btn-outline-dark" href="{% url 'store:store' %}">&#x2190; Continue Shopping</a>

				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{ order.get_cart_items }}</strong></h5></th>
						<th><h5>Total:<strong> ${{ order.get_cart_total }}</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'store:checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{ item.product.imageURL }}"></div>
					<div style="flex:2"><p>{{ item.product.name }}</p></div>
					<div style="flex:1"><p>{{ item.product.price| floatformat:2 }}</p></div>
					<div style="flex:1">
						<p class="quantity">{{ item.quantity }}</p>
						<div class="quantity">
							<img class="chg-quantity update-cart" data-product="{{ item.product.id }}" data-action="add"
							 src="{% static  'images/arrow-up.png' %}">
					
							<img class="chg-quantity update-cart" data-product="{{ item.product.id }}" data-action="remove"
							src="{% static  'images/arrow-down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p>$ {{ item.get_total }}</p></div>
				</div>
				{% endfor %}

			</div>
		</div>
	</div>
{% endblock content %}

templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}

{% block content %}
     <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>
					
					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Country..">
						</div>
					</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>

			<br>
			<div class="box-element hidden" id="payment-info">
				<small>Paypal Options</small>
				<!-- Set up a container element for the button -->
				<div id="paypal-button-container"></div>
				<!--<button id='make-payment'>Make Payment</button>-->
			</div>
			
		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{ item.product.imageURL }}"></div>
					<div style="flex:2"><p>{{ item.product.name }}</p></div>
					<div style="flex:1"><p>$ {{ item.product.price }}</p></div>
					<div style="flex:1"><p>  x{{ item.quantity }}</p></div>
				</div>
				{% endfor %}
				<h5>Items:   {{ order.get_cart_items }}</h5>
				<h5>Total:   $ {{ order.get_cart_total }}</h5>
			</div>
		</div>
	</div>

	<!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=AXC9JHW-5njWFw2gu0wb2cayxBbKOUUTH2quGY6U0-qieRoMhyToMG2fr2YD3vd-ofhp8SrIQ7DscwMA&currency=USD"></script>

	<script>
		var total = "{{ order.get_cart_total | floatformat:2 }}"
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

			style:{
				color: 'blue',
				shape: 'rect',
			},

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: parseFloat(total).toFixed(2)
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
					submitFormData()
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                });
            }


        }).render('#paypal-button-container');

    </script>

	<script type="text/javascript">
		
		var shipping = "{{ order.shipping }}"    
		

		if (shipping == 'False' ){
			document.getElementById('shipping-info').innerHTML = ''
		}

		if (user != 'AnonymousUser'){
			document.getElementById('user-info').innerHTML = ''
			console.log('User is logged!')
		 }

		if (shipping == 'False' && user != 'AnonymousUser'){
			//Hide entire form if user is logged in and shipping is false
			document.getElementById('form-wrapper').classList.add("hidden");
			//Show payment if logged in user wants to buy an item that does not require shipping
			document.getElementById('payment-info').classList.remove("hidden");
		}

		
		var form = document.getElementById('form')

		form.addEventListener('submit', function(e) {  // When the button "Continue" is pressed
			e.preventDefault()
			console.log('Form submmited...')
			document.getElementById('form-button').classList.add('hidden')
			document.getElementById('payment-info').classList.remove('hidden')
		})

		// If the 
		/*
		document.getElementById('make-payment').addEventListener('click', function(e){
			submitFormData()
		})*/


		function submitFormData() {
			console.log('Payment button clicked')
			var userFormData = {
				'name':null,
				'email':null,
				'total':total,
			}

			var shippingInfo = {
				'address':null,
				'city':null,
				'state':null,
				'zipcode':null,
			}

			if (shipping != 'False'){
				shippingInfo.address = form.address.value
				shippingInfo.city = form.city.value
				shippingInfo.state = form.state.value
				shippingInfo.zipcode = form.zipcode.value
			}

			if (user == 'AnonymousUser'){
				userFormData.name = form.name.value
				userFormData.email = form.email.value
			}

			// Make the request to the backend
			var url = '/process_order/'
			fetch(url,{
				method:'POST',
				headers:{
					'Content-Type':'application/json',
					'X-CSRFToken':csrftoken,
				},
				body:JSON.stringify({'form':userFormData, 'shipping':shippingInfo}
				    )

			})
			.then((response) => response.json())
			.then((data) => { // Receive data from Python backend processOrder function
				console.log('success:', data);
				alert('Transaction completed');
				cart = {}
				document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
				window.location.href = "{% url 'store:store' %}"
			})

		}
	</script>

{% endblock content %}

templates/store/main.html
<!DOCTYPE html>

{% load static %}

<html>

<head>
	<title>Ecommerce Bobinados S.A.S.</title>

    <!--Responsive-->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
    <!--Bootstrap-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!--Local css style-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

	<script type="text/javascript">
		var user = '{{request.user}}' // The user is always in all the templates
		
		function getToken(name) {
			var cookieValue = null;
			if (document.cookie && document.cookie !== '') {
				var cookies = document.cookie.split(';');
				for (var i = 0; i < cookies.length; i++) {
					var cookie = cookies[i].trim();
					// Does this cookie string begin with the name we want?
					if (cookie.substring(0, name.length + 1) === (name + '=')) {
						cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
						break;
					}
				}
			}
			return cookieValue;
	    }
		var csrftoken = getToken('csrftoken')

		function getCookie(name) {
		    // Split cookie string and get all individual name=value pairs in an array
		    var cookieArr = document.cookie.split(";");

		    // Loop through the array elements
		    for(var i = 0; i < cookieArr.length; i++) {
		        var cookiePair = cookieArr[i].split("=");

		        /* Removing whitespace at the beginning of the cookie name
		        and compare it with the given string */
		        if(name == cookiePair[0].trim()) {
		            // Decode the cookie value and return
		            return decodeURIComponent(cookiePair[1]);
		        }
		    }

		    // Return null if not found
		    return null;
		}

		var cart = JSON.parse(getCookie('cart'))

		if (cart == undefined){  // When anonymous user enter to the store without items added
			cart = {}
			console.log('Cart Created!', cart)
			document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
		}
		console.log('Cart:', cart)


	</script>

</head>

<body>

		<nav class="navbar navbar-expand-lg navbar-dark bg-dark"><!-- we can switch to light mode changing dark for light--> <!--<img src="{% static "images/bobinados.jpg" %}"  style="max-width: 60%;"> -->
		  <a class="navbar-brand" href="#">Bobinados S.A.S.</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <br>
		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">
		      <li class="nav-item active">
		        <a class="nav-link" href="{% url 'store:store' %}">Store <span class="sr-only">(current)</span></a>
		      </li>
		    </ul>
			<div class="form-inline my-2 my-lg-0">
				<a href="#"class="btn btn-warning">Login</a>
				
				<a href="{% url 'store:cart' %}">
				   <img  id="cart-icon" src="{% static 'images/cart.png' %}">
			   </a>
			   <p id="cart-total">{{ cartItems }}</p>
   
		   </div>
		  </div>
		</nav>

	<div class="container">
	    <br>
	    {% block content %}


	    {% endblock content %}
	</div>


		<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

		<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>  

		
</body>
</html>

templates/store/nodeR.html
{% extends 'store/main.html' %}
{% load static %}

{{ data }}

templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}
<!--{% load crispy_forms_tags %} -->
{% block content %}
{{var.message}}
	<div class="row">
		<div>
			<!-- Form -->
			
			<form action="{% url 'store:store' %}" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="form-row">
					<div class="form-group col-md-2.5 mb-0">
					  {{ form.power|as_crispy_field }}
					</div>
					<div class="form-group col-md-2.5 mb-0">
					  {{ form.speed|as_crispy_field }}
					</div>
					<div class="form-group col-md-3.5 mb-0">
					{{ form.phases|as_crispy_field }}
					</div>
					<div class="form-group col-md-3.5 mb-0">
					{{ form.purpose|as_crispy_field }}
					</div>					
				</div>
				<button type="submit" class="btn btn-primary">Filter!</button>
				<!--<div class="form-group">
					<div class="list-group list-group-horizontal">
						
						{{ form.as_p }}

					</div> -->
				
				<!--<button class="btn btn-primary btn-block mt-5" type="submit">Filter!</button> -->
				
			</form>
		
		</div>
	</div>
	<div class="row">
		{% for product in products %}
		<div class="col-lg-4">
			<img class="thumbnail" src="{{ product.imageURL }}">
			<div class="box-element product">
				<h6><strong>{{ product.name }}</strong></h6>
				<hr>

				<button data-product="{{ product.id }}" data-action="add" class="btn btn-outline-secondary add-btn 
				update-cart">Add to Cart</button>
				<a class="btn btn-outline-success" href="#">View</a>
				<h4 style="display: inline-block; float: right"><strong>$ {{ product.price | floatformat:2 }}</strong></h4>

			</div>
		</div>
		{% endfor %}

	</div>

{% endblock content %}
  